#%RAML 1.0 Library
usage:
types:
  shoppingItemType: 
    properties:
      description: 
        type: string
      itemID:
        type: integer
      itemPrice:
        type: integer
      itemName:
        type: string