#%RAML 1.0
title: Shopping Bazar Pro
version: 1.0
baseUri: api
uses:
  common:
    /exchange_modules/82915fac-aca8-4c8a-8d0b-8344c8524078/common/1.0.2/common.raml
    
/search/items:
   get:
    displayName: Search all items
    description: Get all inventory items regardless of what store the it belongs to.
    responses:
      200:
       body:
          application/json: 
            type: common.shoppingItemType[]
/item/{item_id}:
      get:
        displayName: Get Item
        description: Gets specific item from a specific store.
        responses:
          200:
            body:
              application/json: 
                 type: common.shoppingItemType
      put:
        displayName:  Update Item
        description:  Update existing item
        body:
          application/json:
            type: common.shoppingItemType
        responses:
          201:
            body:
              application/json:
                example: |
                  message: item has been updated
      delete:
        displayName: Delete Item
        description: Delete existing item.
        responses:
          204:
            body:
              application/json:
                examples:
                  message: item has been delted
      post:
        displayName: Add Item
        description: Create a new item for a given store.
        body:
          application/json:
            type: common.shoppingItemType             
        responses:
          201:
            body:
              application/json: